import { User } from "../models/user.model";

export const users: User[] = [
    {
      id: 1,
      profilePhoto: 'https://example.com/avatar1.png',
      firstName: 'Ali',
      lastName: 'Abasi',
      age: 30,
      education: 'Bachelor',
      nationalId: '1234567890',
      birthDate: new Date('1993-05-12'),
    },
    {
      id: 2,
      profilePhoto: 'https://example.com/avatar2.png',
      firstName: 'Reza',
      lastName: 'Moradi',
      age: 25,
      education: 'Master',
      nationalId: '0987654321',
      birthDate: new Date('1998-07-18'),
    },
    {
      id: 3,
      profilePhoto: 'https://example.com/avatar3.png',
      firstName: 'Sara',
      lastName: 'Karimi',
      age: 28,
      education: 'PhD',
      nationalId: '1122334455',
      birthDate: new Date('1995-03-22'),
    },
    {
      id: 4,
      profilePhoto: 'https://example.com/avatar4.png',
      firstName: 'Mehdi',
      lastName: 'Hosseini',
      age: 35,
      education: 'Bachelor',
      nationalId: '2233445566',
      birthDate: new Date('1988-11-05'),
    },
    {
      id: 5,
      profilePhoto: 'https://example.com/avatar5.png',
      firstName: 'Neda',
      lastName: 'Rahimi',
      age: 27,
      education: 'Master',
      nationalId: '3344556677',
      birthDate: new Date('1996-01-15'),
    },
    {
      id: 6,
      profilePhoto: 'https://example.com/avatar6.png',
      firstName: 'Hassan',
      lastName: 'Jafari',
      age: 32,
      education: 'PhD',
      nationalId: '4455667788',
      birthDate: new Date('1991-09-30'),
    },
    {
      id: 7,
      profilePhoto: 'https://example.com/avatar7.png',
      firstName: 'Maryam',
      lastName: 'Ghasemi',
      age: 24,
      education: 'Bachelor',
      nationalId: '5566778899',
      birthDate: new Date('1999-06-12'),
    },
    {
      id: 8,
      profilePhoto: 'https://example.com/avatar8.png',
      firstName: 'Amir',
      lastName: 'Kazemi',
      age: 29,
      education: 'Master',
      nationalId: '6677889900',
      birthDate: new Date('1994-04-25'),
    },
    {
      id: 9,
      profilePhoto: 'https://example.com/avatar9.png',
      firstName: 'Fatemeh',
      lastName: 'Ebrahimi',
      age: 31,
      education: 'PhD',
      nationalId: '7788990011',
      birthDate: new Date('1992-08-19'),
    },
    {
      id: 10,
      profilePhoto: 'https://example.com/avatar10.png',
      firstName: 'Saeed',
      lastName: 'Mohammadi',
      age: 26,
      education: 'Bachelor',
      nationalId: '8899001122',
      birthDate: new Date('1997-12-03'),
    },
    {
      id: 11,
      profilePhoto: 'https://example.com/avatar11.png',
      firstName: 'Leila',
      lastName: 'Ahmadi',
      age: 33,
      education: 'Master',
      nationalId: '9900112233',
      birthDate: new Date('1990-02-28'),
    },
    {
      id: 12,
      profilePhoto: 'https://example.com/avatar12.png',
      firstName: 'Hossein',
      lastName: 'Rostami',
      age: 34,
      education: 'PhD',
      nationalId: '0011223344',
      birthDate: new Date('1989-07-07'),
    },
  ];
  